import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = process.cwd();
const envPath = path.join(root, ".env");

if (fs.existsSync(envPath)) {
  console.log(".env already exists — leaving it untouched.");
  process.exit(0);
}

// Local-only development credentials. Passwords never leave this file.
const password = crypto.randomBytes(9).toString("base64url");
const sessionSecret = crypto.randomBytes(48).toString("base64url");

const contents = `# Generated by scripts/init-env.mjs — local development only.
DATABASE_URL="file:./dev.db"
APP_URL="http://localhost:3111"
SESSION_SECRET="${sessionSecret}"

ADMIN_EMAIL="you@example.com"
ADMIN_PASSWORD="${password}"
USER_TIMEZONE="Asia/Jakarta"

DISCORD_BOT_TOKEN=""
DISCORD_APPLICATION_ID=""
DISCORD_NOTIFY_CHANNEL_ID=""
DISCORD_PUBLIC_KEY=""
DISCORD_GUILD_ID=""

AI_PROVIDER=""
AI_API_KEY=""
AI_MODEL=""
`;

fs.writeFileSync(envPath, contents, { mode: 0o600 });
console.log(`Wrote .env\nLOGIN_EMAIL=you@example.com\nLOGIN_PASSWORD=${password}`);
